name: shingasOrigins
version: '1.0'
main: com.shingaspt.shingasOrigins.ShingasOrigins
api-version: '1.21'
authors: [ShingasPT]
description: Shingas Custom Origin Addon
depend: [Origins-Reborn]
commands:
  vamptoggle:
    description: "Toggles on/off the vampire transformation when killing players."
    usage: "/vamptoggle <on/off>"
  dwarfvision:
    description: "Toggles on/off the dwarf's night vision."
    usage: "/dwarfvision <on/off>"